version: '3.7'
services:
    postgresTest:
      image: postgres:12.9
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=SECDatabaseTest
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5433:5432'
      volumes:
        - ./postgres-data-tests:/var/lib/postgresql/data
        - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql